---
- fail:
    msg: 'azure_lb_name must be specified when attaching nic to load balancer'
  when: azure_lb_name is undefined

- fail:
    msg: 'azure_virtual_network must be specified when attaching nic to load balancer'
  when: azure_virtual_network is undefined

- fail:
    msg: 'azure_subnet must be specified when attaching nic to load balancer'
  when: azure_subnet is undefined    

- name: Lookup VM's NIC
  azure_rm_virtualmachine_info:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vm_name }}"
  register: vm_info      

- fail:
    msg: Could not find network interface for vm '{{ azure_vm_name }}'
  when:
    - vm_info.vms | length == 0 or vm_info.vms[0].network_interface_names | length == 0

- name: Attach NIC to load balancer
  block:
    - set_fact:
        azure_network_interface_name: "{{ vm_info.vms[0].network_interface_names[0] }}"

    - name: Get load balancer info
      azure_rm_loadbalancer_info:
        name: "{{ azure_lb_name }}"
        resource_group: "{{ azure_resource_group }}"
      register: lb_info

    - fail:
        msg: Load balancer '{{ azure_lb_name }}' could not be found
      when:
        - lb_info.ansible_info.azure_loadbalancers | length == 0

    - name: Add Network Interface to Load Balancer
      azure_rm_networkinterface:
        name: "{{ azure_network_interface_name }}"
        resource_group: "{{ azure_resource_group }}"
        virtual_network: "{{ azure_virtual_network }}"
        subnet_name: "{{ azure_subnet }}"
        ip_configurations:
          - name: default
            load_balancer_backend_address_pools:
              - "{{ lb_info.ansible_info.azure_loadbalancers[0].properties.backendAddressPools[0].id }}"
