---
# Azure resource group
azure_resource_group: 'webapp-jt'

# PostgreSQL Server variables
azure_postgresql_name: "{{ azure_resource_group }}-dbserver"
azure_postgresql_admin_username: "ansible"
azure_postgresql_admin_password: "4fB5In3ueO7,"
azure_postgresql_database_instances:
  - name: pyapp
    charset: UTF8

azure_container_registry: "jtwebappcr"
azure_app_src_repo: "https://github.com/joseph-torcasso/webapp_pyflask_demo.git"
azure_app_image_name: "pywebapp"

# Application variables
azure_app_env_vars:
  - name: FLASK_APP
    value: "/app/pyapp"
  - name: FLASK_ENV
    value: "development"
  - name: DATABASE_HOST
    value: "{{ azure_postgresql_name }}"
  - name: DATABASE_INSTANCE
    value: "{{ azure_postgresql_database_instances[0].name }}"
  - name: DATABASE_USER
    value: "{{ azure_postgresql_admin_username }}"
  - name: DATABASE_PASSWORD
    value: "{{ azure_postgresql_admin_password }}"
  - name: ADMIN_USER
    value: "admin"
  - name: ADMIN_PASSWORD
    value: "admin"