---
- name: Test network interface role
  block:
    - name: Test invalid test case - no resource group
      block:
        - name: Attempt to create nic with no resource group - should fail
          block:
            - name: Call azure_manage_network_interface role with no resource group defined
              ansible.builtin.include_role:
                name: cloud.azure_roles.azure_manage_network_interface
              vars:
                operation: create
          rescue:
            - name: Assert correct error message
              ansible.builtin.fail:
                msg: Task failed with incorrect error message
              when: ansible_failed_result.msg is not match("Azure resource group name must be defined as azure_resource_group")

    - name: Set facts
      ansible.builtin.set_fact:
        resource_group: test_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=6') }}
        azure_region: canadacentral
        azure_tags:
          cloud.azure_roles: azure_manage_network_interface

    - name: Attempt to create nic with nonexistent resource group - should fail
      block:
        - name: Call azure_manage_network_interface role with nonexistent resource group
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ resource_group }}-nic"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match(message)
          vars:
            message: Resource group {{ resource_group }} does not exist

        - name: Create resource group
          azure.azcollection.azure_rm_resourcegroup:
            name: "{{ resource_group }}"
            location: "{{ azure_region }}"

    - name: Attempt to create nic with no name - should fail
      block:
        - name: Call azure_manage_network_interface role with no name defined
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match("Missing parameter:\ key 'name' not found in azure_network_interface")

    - name: Attempt to create nic with no vnet name - should fail
      block:
        - name: Call azure_manage_network_interface role with no vnet name defined
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ resource_group }}-nic"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match("Missing parameter:\ key 'vnet_name' not found in azure_network_interface")

    - name: Attempt to create nic with no subnet name - should fail
      block:
        - name: Call azure_manage_network_interface role with no subnet name defined
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ resource_group }}-nic"
              vnet_name: "{{ resource_group }}-vnet"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match("Missing parameter:\ key 'subnet_name' not found in azure_network_interface")

    - name: Set networking facts
      ansible.builtin.set_fact:
        nic_name: "{{ resource_group }}-nic"
        vnet:
          name: "{{ resource_group }}-vnet"
          address_prefixes_cidr:
            - 10.16.0.0/16
          resource_group: "{{ resource_group }}"
        subnet:
          name: "{{ resource_group }}-subnet"
          address_prefix_cidr: 10.16.0.0/24
          resource_group: "{{ resource_group }}"
          virtual_network_name: "{{ resource_group }}-vnet"

    - name: Attempt to create nic with nonexistent virtual network - should fail
      block:
        - name: Call azure_manage_network_interface role with nonexistent virtual network
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"
              vnet_name: "{{ vnet.name }}"
              subnet_name: "{{ subnet.name }}"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match(message)
          vars:
            message: Virtual network {{ vnet.name }} does not exist

        - name: Create vnet
          azure.azcollection.azure_rm_virtualnetwork: "{{ vnet }}"

    - name: Attempt to create nic with nonexistent subnet - should fail
      block:
        - name: Call azure_manage_network_interface role with nonexistent subnet
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"
              vnet_name: "{{ vnet.name }}"
              subnet_name: "{{ subnet.name }}"
      rescue:
        - name: Assert correct error message
          ansible.builtin.fail:
            msg: Task failed with incorrect error message
          when: ansible_failed_result.msg is not match(message)
          vars:
            message: Subnet {{ subnet.name }} does not exist

        - name: Create subnet
          azure.azcollection.azure_rm_subnet: "{{ subnet }}"

    - name: Test valid creation of network interface
      block:
        - name: Create nic with default values
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"
              vnet_name: "{{ vnet.name }}"
              subnet_name: "{{ subnet.name }}"

        - name: Get nic info
          azure.azcollection.azure_rm_networkinterface_info:
            resource_group: "{{ resource_group }}"
          register: nic_info

        - name: Assert that network interface was successfully created
          ansible.builtin.assert:
            that:
              - nic_info.networkinterfaces | length == 1

        - name: Create public ip
          azure.azcollection.azure_rm_publicipaddress:
            resource_group: "{{ resource_group }}"
            name: "{{ resource_group }}-pip"

        - name: Update nic with public ip
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"
              vnet_name: "{{ vnet.name }}"
              subnet_name: "{{ subnet.name }}"
              ip_configurations:
                - name: ipconf1
                  public_ip_address_name: "{{ resource_group }}-pip"
                  primary: true

        - name: Get nic info
          azure.azcollection.azure_rm_networkinterface_info:
            resource_group: "{{ resource_group }}"
          register: nic_info

        - name: Assert that public ip is attached to nic
          ansible.builtin.assert:
            that:
              - nic_info.networkinterfaces | length == 1
              - nic_info.networkinterfaces[0].ip_configurations[0].public_ip_address is search("{{ resource_group }}-pip")

        - name: Test security group parameters
          block:
            - name: Create security group for nic
              azure.azcollection.azure_rm_securitygroup:
                resource_group: "{{ resource_group }}"
                name: "{{ resource_group }}-sg"

            - name: Update nic with security group
              ansible.builtin.include_role:
                name: cloud.azure_roles.azure_manage_network_interface
              vars:
                operation: create
                azure_resource_group: "{{ resource_group }}"
                azure_network_interface:
                  name: "{{ nic_name }}"
                  vnet_name: "{{ vnet.name }}"
                  subnet_name: "{{ subnet.name }}"
                  ip_configurations:
                    - name: ipconf1
                      public_ip_address_name: "{{ resource_group }}-pip"
                      primary: true
                  security_group_name: "{{ resource_group }}-sg"

            - name: Get nic info
              azure.azcollection.azure_rm_networkinterface_info:
                resource_group: "{{ resource_group }}"
              register: nic_info

            - name: Assert that security group is attached to nic
              ansible.builtin.assert:
                that:
                  - nic_info.networkinterfaces | length == 1
                  - nic_info.networkinterfaces[0].security_group is search("{{ resource_group }}-sg")

            - name: Update nic with no default security group
              ansible.builtin.include_role:
                name: cloud.azure_roles.azure_manage_network_interface
              vars:
                operation: create
                azure_resource_group: "{{ resource_group }}"
                azure_network_interface:
                  name: "{{ nic_name }}"
                  vnet_name: "{{ vnet.name }}"
                  subnet_name: "{{ subnet.name }}"
                  ip_configurations:
                    - name: ipconf1
                      public_ip_address_name: "{{ resource_group }}-pip"
                      primary: true
                  create_with_security_group: false

            - name: Get nic info
              azure.azcollection.azure_rm_networkinterface_info:
                resource_group: "{{ resource_group }}"
              register: nic_info

            - name: Assert that security group is removed
              ansible.builtin.assert:
                that:
                  - nic_info.networkinterfaces | length == 1
                  - nic_info.networkinterfaces[0].security_group == None

        - name: Test other nic parameters
          block:
            - name: Update nic with extra params
              ansible.builtin.include_role:
                name: cloud.azure_roles.azure_manage_network_interface
              vars:
                operation: create
                azure_resource_group: "{{ resource_group }}"
                azure_network_interface:
                  name: "{{ nic_name }}"
                  vnet_name: "{{ vnet.name }}"
                  subnet_name: "{{ subnet.name }}"
                  ip_configurations:
                    - name: ipconf1
                      public_ip_address_name: "{{ resource_group }}-pip"
                      primary: true
                  security_group_name: "{{ resource_group }}-sg"
                  os_type: Windows
                  enable_accelerated_networking: true
                  ip_forwarding: true
                  dns_servers:
                    - 8.8.8.8

            - name: Get nic info
              azure.azcollection.azure_rm_networkinterface_info:
                resource_group: "{{ resource_group }}"
              register: nic_info

            - name: Assert that extra params were set properly
              ansible.builtin.assert:
                that:
                  - nic_info.networkinterfaces | length == 1
                  - nic_info.networkinterfaces[0].enable_accelerated_networking == true
                  - nic_info.networkinterfaces[0].enable_ip_forwarding == true
                  - nic_info.networkinterfaces[0].dns_servers[0] == '8.8.8.8'

    - name: Test cleanup of network interface resources
      block:
        - name: Delete network interface
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: delete
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"

        - name: Get nic info
          azure.azcollection.azure_rm_networkinterface_info:
            resource_group: "{{ resource_group }}"
          register: nic_info

        - name: Get sg info
          azure.azcollection.azure_rm_securitygroup_info:
            resource_group: "{{ resource_group }}"
          register: sg_info

        - name: Assert that network interface was deleted and its default security group does not exist
          ansible.builtin.assert:
            that:
              - "{{ nic_name not in nic_info.networkinterfaces | map(attribute='name') }}"
              - "{{ nic_name not in sg_info.securitygroups | map(attribute='name') }}"

        - name: Create nic with default security group
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: create
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"
              vnet_name: "{{ vnet.name }}"
              subnet_name: "{{ subnet.name }}"

        - name: Get nic info
          azure.azcollection.azure_rm_networkinterface_info:
            resource_group: "{{ resource_group }}"
          register: nic_info

        - name: Get sg info
          azure.azcollection.azure_rm_securitygroup_info:
            resource_group: "{{ resource_group }}"
          register: sg_info

        - name: Assert that network interface was created with its default security group
          ansible.builtin.assert:
            that:
              - "{{ nic_name in nic_info.networkinterfaces | map(attribute='name') }}"
              - "{{ nic_name in sg_info.securitygroups | map(attribute='name') }}"

        - name: Delete nic & its security group
          ansible.builtin.include_role:
            name: cloud.azure_roles.azure_manage_network_interface
          vars:
            operation: delete
            azure_resource_group: "{{ resource_group }}"
            azure_network_interface:
              name: "{{ nic_name }}"

        - name: Get nic info
          azure.azcollection.azure_rm_networkinterface_info:
            resource_group: "{{ resource_group }}"
          register: nic_info

        - name: Get sg info
          azure.azcollection.azure_rm_securitygroup_info:
            resource_group: "{{ resource_group }}"
          register: sg_info

        - name: Assert that network interface and its security group were deleted
          ansible.builtin.assert:
            that:
              - "{{ nic_name not in nic_info.networkinterfaces | map(attribute='name') }}"
              - "{{ nic_name not in sg_info.securitygroups | map(attribute='name') }}"

  always:
    - name: Delete resource group # noqa ignore-errors
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent
        force_delete_nonempty: true
      ignore_errors: true
