---
- set_fact:
    docker_group: "docker"

- name: Install system packages
  yum:
    name:
      - yum-utils
  become: true

- name: Add docker repository
  shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    warn: false
  become: true

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true

- name: Ensure "docker" group exists
  group:
    name: "{{ docker_group }}"
    state: present
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups:
      - "{{ docker_group }}"
    append: yes
  become: true

- name: Assure docker service is running
  service:
    name: docker
    enabled: yes
    state: started
  become: true

- name: Assure docker.socket service is running
  service:
    name: docker.socket
    enabled: yes
    state: started
  failed_when: false
  become: true

- name: Correct group ownership on docker sock
  file:
    path: /var/run/docker.sock
    group: "{{ docker_group }}"
  become: true

- name: Validate ability to talk with docker
  command: docker run hello-world
  changed_when: false
  args:
    warn: no
