---
- name: Converge
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: test resource_group role
      include_tasks:
        file: tasks/resource_group.yml
        apply:
          tags:
            - resource_group
      tags:
        - always
    - name: test networking_stack role
      include_tasks:
        file: tasks/networking_stack.yml
        apply:
          tags:
            - networking_stack
      tags:
        - always
