---
- name: Converge
  hosts: localhost
  tasks:
    - name: Test resource_group role
      ansible.builtin.include_tasks:
        file: tasks/resource_group.yml
        apply:
          tags:
            - resource_group
      tags:
        - always

    - name: Test networking_stack role
      ansible.builtin.include_tasks:
        file: tasks/networking_stack.yml
        apply:
          tags:
            - networking_stack
      tags:
        - always

    - name: Test managed_postgresql role
      ansible.builtin.include_tasks:
        file: tasks/managed_postgresql.yml
        apply:
          tags:
            - managed_postgresql
      tags:
        - always

    - name: Test virtual_machine role
      ansible.builtin.include_tasks:
        file: tasks/virtual_machine.yml
        apply:
          tags:
            - virtual_machine
      tags:
        - always

    - name: Test network_interface role
      ansible.builtin.include_tasks:
        file: tasks/network_interface.yml
        apply:
          tags:
            - network_interface
      tags:
        - always

    - name: Test load_balancer role
      ansible.builtin.include_tasks:
        file: tasks/load_balancer.yml
        apply:
          tags:
            - load_balancer
      tags:
        - always

    - name: Test security_group role
      ansible.builtin.include_tasks:
        file: tasks/security_group.yml
        apply:
          tags:
            - security_group
      tags:
        - always
