---
name: CI
'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:

  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7']
        ansible_version: ['stable-2.11', 'stable-2.10', 'stable-2.9', 'devel']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -e linters -vv
